### ISSUE TITLE
Use of pytorch_pretrained_bert in XLNet Notebook

### ISSUE THREAD

**Issue by ChrisPalmerNZ** [billpku/NLP_In_Action#1]
Can the notebook be harmonized to just use the `pytorch_transformers` and not rely on the earlier `pytorch_pretrained_bert`? 

1. You would need to import and use AdamW from the new library, rather than BertAdam from the old one, or remove that import altogether since you later just use the Adam optimizer

2. The XLNetForSequenceClassification.from_pretrained requires the model name - the definition is from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs): 
```
model = XLNetForSequenceClassification.from_pretrained('xlnet-base-cased', model_file_address,num_labels=len(tag2idx))
```
3. Unsure if this is due to a model change, but there is no classifier layer in the model, so the call to `param_optimizer = list(model.classifier.named_parameters())` fails when `FULL_FINETUNING` is set to `False`.

**Comment by billpku** [comment]
> Can the notebook be harmonized to just use the `pytorch_transformers` and not rely on the earlier `pytorch_pretrained_bert`?
> 
> 1. You would need to import and use AdamW from the new library, rather than BertAdam from the old one, or remove that import altogether since you later just use the Adam optimizer
> 2. The XLNetForSequenceClassification.from_pretrained requires the model name - the definition is from_pretrained(cls, pretrained_model_name_or_path, *inputs, **kwargs):
> 
> ```
> model = XLNetForSequenceClassification.from_pretrained('xlnet-base-cased', model_file_address,num_labels=len(tag2idx))
> ```
> 
> 1. Unsure if this is due to a model change, but there is no classifier layer in the model, so the call to `param_optimizer = list(model.classifier.named_parameters())` fails when `FULL_FINETUNING` is set to `False`.

Hi,

Thank you for your feedback.

1. You can use 'pytorch_transformers' instead of `pytorch_pretrained_bert`, it will be easy to  get the new code to work only need a small change, and I will update the code later, since hugging face team had change the `pytorch_pretrained_bert` to 'pytorch_transformers', and it also need  the change of BertAdam optimizer as you suggest.

2. For the XLNetForSequenceClassification.from_pretrained() function, yes, you can set to load the model name with 'xlnet-base-cased'  or 'xlnet-large-cased'. If you have download the model into your local folder like me, you can set the model folder address instead, cause with the way, I can load my personal LM-fine-tuned model.

3. Yes, you remind me, since the XLNET model in 'pytorch_transformers' did not contain a classifier, FULL_FINETUNING need to set to True.

Thank you for your suggestion.
