### ISSUE TITLE
The initialization of BertForTokenClassification,'NoneType' object is not iterable

### ISSUE THREAD

**Issue by roothch** [billpku/NLP_In_Action#2]
I met the following error when I try to run the code:
Traceback (most recent call last):
  File "train.py", line 152, in <module>
    model = BertForTokenClassification.from_pretrained(r"/home/ky01/hzh/bert_model/bert-base-cased",num_labels=len(tag2idx))
  File "/home/ky01/.conda/envs/hzh_python/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 430, in from_pretrained
    **kwargs
TypeError: 'NoneType' object is not iterable

**Comment by billpku** [comment]
> I met the following error when I try to run the code:
> Traceback (most recent call last):
> File "train.py", line 152, in
> model = BertForTokenClassification.from_pretrained(r"/home/ky01/hzh/bert_model/bert-base-cased",num_labels=len(tag2idx))
> File "/home/ky01/.conda/envs/hzh_python/lib/python3.6/site-packages/pytorch_transformers/modeling_utils.py", line 430, in from_pretrained
> **kwargs
> TypeError: 'NoneType' object is not iterable

Hi,

I assert that you had downloaded the  pretrianed model then renamed the model files and vocabulary files name as required.
I found that you use absolute address"/home/ky01/hzh/bert_model/bert-base-cased",  what about using relative path instead. Maybe you can fix the problem.

Feel free to leave a comment.

**Comment by roothch** [comment]
Thank you.I update the pytorch-transformer to version 1.2.0,which also solve the problem

**Comment by Mayar2009** [comment]
Hi !
I have a problem also when I use these lines of code
model_file_address = '/content/drive/My Drive/Colab Notebooks/bert-base-cased'
model = BertForTokenClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))


The error is 
---------------------------------------------------------------------------
OSError: Error no file named ['pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'] found in directory /content/drive/My Drive/Colab Notebooks/bert-base-cased or `from_tf` set to False

actually I download pretrained model from here 
https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip

I think I miss something

**Comment by Mayar2009** [comment]
from where am I supposed to download the prerained model it is not clear to me
could you tell me please?

**Comment by billpku** [comment]
> from where am I supposed to download the prerained model it is not clear to me
> could you tell me please?
@Mayar2009 

Since this notebook use Pytorch as backend library, we need to download the BERT for Pytorch model first.

_Thank you for your suggestion, I had updated my notebook with the required files download address._

**To make the model load successfully.**
- I suppose your model folder is "/content/drive/My Drive/Colab Notebooks/bert-base-cased"
- You need to download the model tokenizer file, model config and model weight into the folder, and rename them as required.
```
# Tokenizer file, vocab.txt
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt

# Model config, config.json
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json

# Model weight, pytorch_model.bin
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin

```

Feel free to leave a comment if it work for you. 
And thank you for your suggestion.

**Comment by Mayar2009** [comment]
Thanks for your reply!
Actually what I have done before your answer is just installing the pretrained model of bert 
https://storage.googleapis.com/bert_models/2018_10_18/cased_L-12_H-768_A-12.zip
unzip it then load its contents to the directory /content/drive/My Drive/Colab Notebooks/bert-base-cased
actually there are 5 files there which are (vocab.txt,  config.json, bert_model.ckpt.data-00000-of-00001, bert_model.ckpt.index, bert_model.ckpt.meta) 
and used vocab.text file from there for this line 

vocabulary = "/content/drive/My Drive/Colab Notebooks/bert-base-cased/vocab.txt"
then I tried like metioned in this link
https://github.com/huggingface/transformers#Migrating-from-pytorch-pretrained-bert-to-transformers
**just write like this**

model_file_address = 'bert-base-cased'  # will load directly from transformer
model = BertForTokenClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))
and the code worked but the truth I did not understand what is going on 
because 
1) vocab.txt is loaded from bert github
2) weights loaded from transformer library
and I did not know if they are supposed to be from the same folder 
getting me?

It also ask for this files

'pytorch_model.bin', 'tf_model.h5', 'model.ckpt.index'

Actually I need to understand from which repository to get files from Bert or Transformers and how .
Thank you for your help to offer files but actually it will be more helpful for the reader to understand how the things is going on

**Comment by Mayar2009** [comment]
I tried to download these links But I am not so experienced as it is clear 
could you please tell me how to do that?
how to download 
# Tokenizer file, vocab.txt
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-vocab.txt

# Model config, config.json
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-config.json

# Model weight, pytorch_model.bin
https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-cased-pytorch_model.bin

>

**Comment by billpku** [comment]
@Mayar2009

1. About BERT Pytorch model
- The library [huggingface/transformers](https://github.com/huggingface/transformers),had already transformed all Google BERT model into Pytorch versoin.
- You can find all the supported model and their download addresses in [modeling_bert.py](https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py)

2. About loading BERT model
```
model = BertForTokenClassification.from_pretrained(model_file_address,num_labels=len(tag2idx))
```
- The first input for the "BertForTokenClassification.from_pretrained()" function is the model name, when the name is in the supported model list, E.g: "bert-base-uncased", "bert-large-uncased"... it will directly load the required files from your local cache folder.
- If you didn't have the files in local cache folder, it will auto download the required files into local cache folder
- If the name is not the supported model name, the function will treat the input as a manual model folder name. As what I did in the notebook, I firstly downloaded all the required files in a folder, then I pass the folder address to the function, the function can  still load the model
- When you load the model with "BertForTokenClassification.from_pretrained()" function, the logger may print warn for some files, don't be worry, if you can load the model successfully, you can ignore it.

**Comment by Mayar2009** [comment]
from your local cache folder.--> you mean by that the models downloaded by transformers library, yeah?

**Comment by billpku** [comment]
> from your local cache folder.--> you mean by that the models downloaded by transformers library, yeah?

@Mayar2009 
Yeah, the transformers will make a cache folder then download the require files for you.
For the default cache file location, check this out [Where does the pre-trained bert model gets cached in my system by default](https://github.com/huggingface/transformers/issues/2323)

**Comment by Mayar2009** [comment]
Thank you! you are great!
