### ISSUE TITLE
What's the X means in tags? did it means the words start with "##"?

### ISSUE THREAD

**Issue by Cung806** [billpku/NLP_In_Action#4]
What's the X means in tags? did it means the words start with "##"? I don't understand.

**Comment by billpku** [comment]
> What's the X means in tags? did it means the words start with "##"? I don't understand.

Yes, you are right
I suppose you are asking the tag definition for "NER with BERT"

Since BERT use word piece method as tokenizer, it will some time break the words into pieces:
E.g:
Sentence: Jim Henson was a puppeteer.
After word piece tokenized: Jim Hen ##son was a puppet ##eer
(This example was from [BERT paper](https://arxiv.org/abs/1810.04805) )

So that, in the process of NER, we need to set a tag like:"X" for the word piece begin with "##"
  
Hope this can help you.

**Comment by Cung806** [comment]
Thanks a lot @billpku
