### ISSUE TITLE
small question please:)

### ISSUE THREAD

**Issue by Mayar2009** [billpku/NLP_In_Action#7]
excuse me for this question but I still learning
what is the meaning of these lines
1)  %reload_ext autoreload
     %autoreload 2
2) !pip list | grep -E 'transformers|torch|Keras' as I understand it lists all libraries related to transformers, torch, Keras with their versions but I mean explanation about the instruction and to use it if it is possible

could you please explain in detail?

**Comment by billpku** [comment]
> excuse me for this question but I still learning
> what is the meaning of these lines
> 
> 1. %reload_ext autoreload
>    %autoreload 2
> 2. !pip list | grep -E 'transformers|torch|Keras' as I understand it lists all libraries related to transformers, torch, Keras with their versions but I mean explanation about the instruction and to use it if it is possible
> 
> could you please explain in detail?

Sure.

**1. These are magic commands line for Jupyter notebook.**
```
%reload_ext autoreload
```
This command enable notebook to auto load the libraries you imported, it will be very helpful when you change you libraries, you will not need to restart your jupyter kernel to make it take effect.

E.g: 

- You just run "import transformers", and the library version is 2.0.0.
- If you just pip install a higher version of transformers==2.2.0, and you want to use it.
- You don't need to restart the notebook to make the new library work.
- You just run the ''import transformers'' again, and the transformers==2.2.0 will come into effect.

```
%autoreload 2
```
This command line mean that the notebook will  autoload the library in every 2 second

_For more detail, feel free to check [autoreload-explain](https://ipython.org/ipython-doc/3/config/extensions/autoreload.html)._

**2. These  are normal linux command lines.**
```
pip list 
```
List all the library of the python env

```
pip list | grep XXX
```

- The "|" work as a connection for  2 command line,"AA | BB" mean that firstly run "AA" then run "BB" based on AA results.
- "grep XXX" means get the content containing "XXX".
- "pip list | grep XXX" means first get all the library of the python env  info and then  only get the "XXX" info.


```
grep -E 'transformers|torch|Keras' 
```
"-E" mean a function for grep, it will enable grep to treat the content "transformers|torch|Keras" as a regular expression, so that the grep can get "transformers" or "torch" or "Keras" contents.


**Hope this can help you.**

**Comment by Mayar2009** [comment]
Yes, it was very helpful! 
thank you very much! I grabbed a lot of information yesterday and today thank you very much!
