### ISSUE TITLE
help can not find csv file!

### ISSUE THREAD

**Issue by Mayar2009** [billpku/NLP_In_Action#8]
I use colab when I use this 

!wget --no-check-certificate \ https://github.com/billpku/NLP_In_Action/tree/master/data/ner_dataset.csv \-O "/data/ner_dataset.csv"

I get this error 
 https://github.com/billpku/NLP_In_Action/tree/master/data/ner_dataset.csv: Scheme missing.

**Comment by billpku** [comment]
> I use colab when I use this
> 
> !wget --no-check-certificate \ https://github.com/billpku/NLP_In_Action/tree/master/data/ner_dataset.csv -O "/data/ner_dataset.csv"
> 
> I get this error
> https://github.com/billpku/NLP_In_Action/tree/master/data/ner_dataset.csv: Scheme missing.

Based to your report, seem like this is a wget usage error.
A solution on the web is  [getting-scheme-missing-error-with-wget](https://askubuntu.com/questions/758080/getting-scheme-missing-error-with-wget)

If you want to use the data quickly, its highly recommended to use git clone:
```
git clone https://github.com/billpku/NLP_In_Action
```
So that you can get all the notebooks and data files.
Then you can move the specific data files to your colab data folder you had made.

**Comment by Mayar2009** [comment]
thanks!
